[project]
name = "getmeadow"
version = "1.0.5"
description = "Python client for the getmeadow api"
readme = "README.md"
authors = [
    { name = "Sebash", email = "sebash@mail.friendlyautomations.com" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.urls]
Homepage = "https://github.com/sebash77/getmeadow"
Repository = "https://github.com/sebash77/getmeadow"
Issues = "https://github.com/sebash77/getmeadow/issues"

