class MeadowEndpoints:
    token = "https://admin.getmeadow.com/api/users/tokens"
    orders = "https://api.getmeadow.com/organizations/{org_id}/orders"
    order = "https://api.getmeadow.com/organizations/{org_id}/orders/{order_id}"
    pusher_auth = "https://api.getmeadow.com/pusher/auth"
    me = "https://api.getmeadow.com/users/me"
    roles = "https://api.getmeadow.com/users/me/roles"
    reports = "https://api.getmeadow.com/organizations/{org_id}/reports"
    inventory_locations = "https://api.getmeadow.com/organizations/{org_id}/inventory-locations"
    inventory_vendors = "https://api.getmeadow.com/organizations/{org_id}/inventory-vendors"
    inventory_vendor = "https://api.getmeadow.com/organizations/{org_id}/inventory-vendors/{vendor_id}"
    inventory = "https://daffodil.getmeadow.com/organizations/{org_id}/products/all"
    discounts = "https://api.getmeadow.com/organizations/{org_id}/discounts"
    delivery_zone_addresses = "https://api.getmeadow.com/organizations/{org_id}/delivery-zones/addresses"
    users = "https://api.getmeadow.com/organizations/{org_id}/users"
    inventory_transactions = " https://api.getmeadow.com/organizations/{org_id}/inventory-transactions"
    user_search = users + "/search"
    full = "https://api.getmeadow.com/organizations/{org_id}/full"
    user_documents = "https://api.getmeadow.com/organizations/{org_id}/users/{user_id}/documents"
    recent_address = "https://api.getmeadow.com/organizations/{org_id}/users/{user_id}/addresses/recent"
    pricing = "https://api.getmeadow.com/organizations/{org_id}/pricing"
    create_customer = "https://admin.getmeadow.com/customers/create"
    sign_s3 = "https://api.getmeadow.com/organizations/{org_id}/general/sign-s3"
    prod_document = "https://s3.us-west-2.amazonaws.com/meadow-documents-production"
    brands = "https://api.getmeadow.com/organizations/{org_id}/brands"
    products = "https://api.getmeadow.com/organizations/{org_id}/products"
    product = "https://api.getmeadow.com/organizations/{org_id}/products/{product_id}"
    product_options = "https://api.getmeadow.com/organizations/{org_id}/products/{product_id}/options"
    product_categories = "https://api.getmeadow.com/organizations/{org_id}/product-categories"
    all_product_categories = product_categories + "/all"
    purchase_orders = "https://api.getmeadow.com/organizations/{org_id}/purchase-orders"
    purchase_order = "https://api.getmeadow.com/organizations/{org_id}/purchase-orders/{po_id}"
    purchase_order_payment = "https://api.getmeadow.com/organizations/{org_id}/purchase-orders/{po_id}/payments"
    purchase_order_receive = "https://api.getmeadow.com/organizations/{org_id}/purchase-orders/{po_id}/receive"
    reconciliations = "https://api.getmeadow.com/organizations/{org_id}/reconciliations"
    vendors = "https://api.getmeadow.com/organizations/{org_id}/inventory-vendors"
    metrc_compliance_transfer_sync = "https://api.getmeadow.com/organizations/{org_id}/compliance-transfers/sync"
    compliance_transfers = "https://api.getmeadow.com/organizations/{org_id}/compliance-transfers"
    compliance_transfer = "https://api.getmeadow.com/organizations/{org_id}/compliance-transfers/{compliance_transfer_id}"
    packages = "https://api.getmeadow.com/organizations/{org_id}/packages"
    customer_groups = "https://api.getmeadow.com/organizations/{org_id}/customer-groups/"
    customer_group_users = "https://api.getmeadow.com/organizations/{org_id}/customer-groups/{group_id}/users"
    customer_group_user = "https://api.getmeadow.com/organizations/{org_id}/customer-groups/{group_id}/users/{user_id}"


class IamIntercomEndpoints:
    web_ping = "https://api-iam.intercom.io/messenger/web/ping"